### ISSUE TITLE
Suggestion: Include pagination in Sitemap

### ISSUE THREAD

**Issue by m2de** [dewsign/nova-blog#13]
In order to make all content easily accessible to Search Engines we should register all paginated pages in the Sitemap, mirroring the BlogController functionality which is already customisable through a config value to set the page size.

As it would just be a new feature and not break any existing functionality we could push this as a standalone minor version upgrade.

Any thoughts / input @tristanward @crumb1e ?

**Comment by tristanward** [comment]
That sounds like a good idea to me @m2de , should be a nice little PR.
